services:
  - type: web
    name: kiau-hoosh-bot
    env: node
    buildCommand: npm install --include=dev && npm run build
    startCommand: npx prisma migrate deploy && npm run start
    healthCheckPath: /health
    autoDeploy: true
